import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Notes App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex h-screen'>
        <div className='m-auto'>
          <h3 className='text-lg underline text-blue-500'>NOTES APP</h3>
          <button className='px-4 py-2 rounded-xl font-medium text-white bg-blue-600 hover:bg-blue-800 active:bg-grey-900 focus:outline-none border-4 border-white focus:border-blue-200 transition-all'>
            Redux
          </button>
        </div>
      </div>
    </>
  );
}
